name: Run tests and deploy

on:
  push:
    paths:
      - '**.js'
      - '**.json'
      - '**.yaml'
    branches:
      - coolify
concurrency:
  group: staging_environment
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Install Docker Compose
          run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version

        - name: Start Postgres and Adminer
          run: docker-compose up -d mongodb

        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Restore Dependencies for web-api
          run: npm ci

        - name: Run Tests for app/web-api
          run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update source commit SHA in Coolify
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.COOLIFY_URL }}
          method: PATCH
          bearerToken: ${{ secrets.COOLIFY_API_TOKEN }}
          data: >-
            {
            "git_commit_sha": "${{ github.sha }}"
            }

      - name: Trigger Coolify deployment via webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.COOLIFY_URL }}
          method: GET
          bearerToken: ${{ secrets.COOLIFY_API_TOKEN }}